source 'https://rubygems.org'

gem 'html-proofer', '~> 4.4'
gem 'github-pages', '~> 231'
gem 'jekyll-redirect-from', '~> 0.16'
gem 'jekyll-scholar', '~> 5.14'
gem 'jekyll-seo-tag', '~> 2.8'
gem 'jekyll-sitemap', '~> 1.4'
gem 'pygments.rb', '~> 3.0'
gem 'rake', '>= 12.3.3'
gem 'unicode'
